name: json_editor_web
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_hooks: ^0.20.4
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  json_annotation: ^4.9.0
  url_launcher: ^6.0.20

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
