name: Download Artifact from Previous Workflow

on:
  workflow_run:
    workflows: ["Build Web"]
    types:
      - completed  

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: WEB_BUILD 
